# Docker


trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    
    - task: Docker@2
      inputs:
        containerRegistry: $(CONTAINER_REGISTRY)
        repository: $(IMAGES_REPOSITORY)
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        tags: 'frontend'
        
    - task: Docker@2
      inputs:
        containerRegistry: $(CONTAINER_REGISTRY)
        repository: $(IMAGES_REPOSITORY)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'backend'