# Docker


trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker HUB ystejamx'
        repository: 'ytsejamx/ytsejamx-registry'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        tags: 'frontend'