# Docker


trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      displayName: 'Build and push image to my registry'
      inputs:
        containerRegistry: 'Docker HUB ystejamx'
        repository: 'ytsejamx/ytsejamx-registry'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        # Build a Docker image 
        # https://docs.microsoft.com/azure/devops/pipelines/languages/docker