# Docker
- task: Docker@2
  inputs:
    containerRegistry: 'Docker HUB ystejamx'
    repository: 'ytsejamx-registry'
    command: 'buildAndPush'
    Dockerfile: '**/frontend/Dockerfile'
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
        tags: |
          $(tag)