version: "2"
services:
  frontend:
    image: ytsejamx/ytsejamx-registry:frontend
    restart: always
    ports:
      - "80:80"
    working_dir: /frontend  

  database:
    image: store/oracle/database-enterprise:12.2.0.1
    restart: always
    ports:
    - "1521:1521"