version: "2"
services:
  frontend:
    image: ytsejamx/ytsejamx-registry:frontend
    restart: always
    ports:
      - "80:80"
    working_dir: /frontend

  db:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    restart: always
    ports:
      - "1521:1521"
    volumes:
      - /opt/oracle/oradata:/home/oracle

  backend:
    build: .
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
    - "5000:5000"