# Use it in deployment, where images must be downloaded from registry
version: "3.7"
services:
  frontend:
    image: ${DOCKER_REGISTRY_AND_REPOSITORY}:frontend
    restart: always
    ports:
      - "80:80"
    working_dir: /frontend

  backend:
    image: ${DOCKER_REGISTRY_AND_REPOSITORY}:backend
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:5.7.32
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
    volumes:
      - ${DB_MOUNTPATH}:/var/lib/mysql

#    Use this container for connecting to this container
#    using Azure ssh feature. Thanks to this, we can
#    interact with other running containers in the same
#    vnet and for example connect to production DB. SSH
#    service should be enabled in frontend container,
#    aka container working on port 80. ticket 55.
#    sshd:
#      image: appsvc/node:latest
#      ports:
#        - "2222:2222"
#        - "80:8080"